# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift', '~> 3.6.1'
  pod 'RxCocoa', '~> 3.6.1'
  pod 'RxDataSources'
  pod 'NSObject+Rx'
  
  pod 'Moya/RxSwift', '~> 8.0.5'
  pod 'ObjectMapper', '~> 2.2.8'
  
  # Pods for RxSwiftDemo

end
